version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "guatepass-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-$(aws sts get-caller-identity --query Account --output text)"
s3_prefix = "guatepass-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
resolve_s3 = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []
